### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vaibhav1307** [shaw4/tidal-rpc#2]
idk why man but the issue still persists.. Am i missing something to do ..like editing any config file.?? the executable just opens and closes instantly :(

**Comment by vars1ty** [comment]
Tested and works now.
To make it work, follow these instructions:
1. Download the EXE and its DLLs
2. Run the EXE
3. Start TIDAL and any song you want
4. Done

**Comment by vaibhav1307** [comment]
> Tested and works now.
> To make it work, follow these instructions:
> 
> 1. Download the EXE and its DLLs
> 2. Run the EXE
> 3. Start TIDAL and any song you want
> 4. Done

sorry to bug you again and again but its still the same... i downloaded the latest zip and ran the executable and it still force closes..
